//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGW.Portal.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityDataContract", Namespace="http://schemas.datacontract.org/2004/07/SGWServices")]
    [System.SerializableAttribute()]
    public partial class EntityDataContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SGW.Portal.ServiceReference1.EntityValueDataContract[] DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid EntityIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SGW.Portal.ServiceReference1.EntityValueDataContract[] Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid EntityId {
            get {
                return this.EntityIdField;
            }
            set {
                if ((this.EntityIdField.Equals(value) != true)) {
                    this.EntityIdField = value;
                    this.RaisePropertyChanged("EntityId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityValueDataContract", Namespace="http://schemas.datacontract.org/2004/07/SGWServices")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SGW.Portal.ServiceReference1.EntityDataContract))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SGW.Portal.ServiceReference1.EntityValueDataContract[]))]
    public partial class EntityValueDataContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Field {
            get {
                return this.FieldField;
            }
            set {
                if ((object.ReferenceEquals(this.FieldField, value) != true)) {
                    this.FieldField = value;
                    this.RaisePropertyChanged("Field");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IEntity")]
    public interface IEntity {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntity/NewManualEntityInstance", ReplyAction="http://tempuri.org/IEntity/NewManualEntityInstanceResponse")]
        SGW.Portal.ServiceReference1.NewManualEntityInstanceResponse NewManualEntityInstance(SGW.Portal.ServiceReference1.NewManualEntityInstanceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntity/NewManualEntityInstance", ReplyAction="http://tempuri.org/IEntity/NewManualEntityInstanceResponse")]
        System.Threading.Tasks.Task<SGW.Portal.ServiceReference1.NewManualEntityInstanceResponse> NewManualEntityInstanceAsync(SGW.Portal.ServiceReference1.NewManualEntityInstanceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntity/ProcessWorkflows", ReplyAction="http://tempuri.org/IEntity/ProcessWorkflowsResponse")]
        SGW.Portal.ServiceReference1.ProcessWorkflowsResponse ProcessWorkflows(SGW.Portal.ServiceReference1.ProcessWorkflowsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntity/ProcessWorkflows", ReplyAction="http://tempuri.org/IEntity/ProcessWorkflowsResponse")]
        System.Threading.Tasks.Task<SGW.Portal.ServiceReference1.ProcessWorkflowsResponse> ProcessWorkflowsAsync(SGW.Portal.ServiceReference1.ProcessWorkflowsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntity/ProcessEmails", ReplyAction="http://tempuri.org/IEntity/ProcessEmailsResponse")]
        SGW.Portal.ServiceReference1.ProcessEmailsResponse ProcessEmails(SGW.Portal.ServiceReference1.ProcessEmailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntity/ProcessEmails", ReplyAction="http://tempuri.org/IEntity/ProcessEmailsResponse")]
        System.Threading.Tasks.Task<SGW.Portal.ServiceReference1.ProcessEmailsResponse> ProcessEmailsAsync(SGW.Portal.ServiceReference1.ProcessEmailsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="NewManualEntityInstance", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class NewManualEntityInstanceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public SGW.Portal.ServiceReference1.EntityDataContract entity;
        
        public NewManualEntityInstanceRequest() {
        }
        
        public NewManualEntityInstanceRequest(SGW.Portal.ServiceReference1.EntityDataContract entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="NewManualEntityInstanceResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class NewManualEntityInstanceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool NewManualEntityInstanceResult;
        
        public NewManualEntityInstanceResponse() {
        }
        
        public NewManualEntityInstanceResponse(bool NewManualEntityInstanceResult) {
            this.NewManualEntityInstanceResult = NewManualEntityInstanceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProcessWorkflows", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ProcessWorkflowsRequest {
        
        public ProcessWorkflowsRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProcessWorkflowsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ProcessWorkflowsResponse {
        
        public ProcessWorkflowsResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProcessEmails", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ProcessEmailsRequest {
        
        public ProcessEmailsRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProcessEmailsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ProcessEmailsResponse {
        
        public ProcessEmailsResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEntityChannel : SGW.Portal.ServiceReference1.IEntity, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EntityClient : System.ServiceModel.ClientBase<SGW.Portal.ServiceReference1.IEntity>, SGW.Portal.ServiceReference1.IEntity {
        
        public EntityClient() {
        }
        
        public EntityClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EntityClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EntityClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EntityClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SGW.Portal.ServiceReference1.NewManualEntityInstanceResponse NewManualEntityInstance(SGW.Portal.ServiceReference1.NewManualEntityInstanceRequest request) {
            return base.Channel.NewManualEntityInstance(request);
        }
        
        public System.Threading.Tasks.Task<SGW.Portal.ServiceReference1.NewManualEntityInstanceResponse> NewManualEntityInstanceAsync(SGW.Portal.ServiceReference1.NewManualEntityInstanceRequest request) {
            return base.Channel.NewManualEntityInstanceAsync(request);
        }
        
        public SGW.Portal.ServiceReference1.ProcessWorkflowsResponse ProcessWorkflows(SGW.Portal.ServiceReference1.ProcessWorkflowsRequest request) {
            return base.Channel.ProcessWorkflows(request);
        }
        
        public System.Threading.Tasks.Task<SGW.Portal.ServiceReference1.ProcessWorkflowsResponse> ProcessWorkflowsAsync(SGW.Portal.ServiceReference1.ProcessWorkflowsRequest request) {
            return base.Channel.ProcessWorkflowsAsync(request);
        }
        
        public SGW.Portal.ServiceReference1.ProcessEmailsResponse ProcessEmails(SGW.Portal.ServiceReference1.ProcessEmailsRequest request) {
            return base.Channel.ProcessEmails(request);
        }
        
        public System.Threading.Tasks.Task<SGW.Portal.ServiceReference1.ProcessEmailsResponse> ProcessEmailsAsync(SGW.Portal.ServiceReference1.ProcessEmailsRequest request) {
            return base.Channel.ProcessEmailsAsync(request);
        }
    }
}
